-- R20 per-role tables migration (generated from gen_create_tables.py)
-- Idempotent: CREATE TABLE IF NOT EXISTS. DO NOT edit by hand.

CREATE TABLE IF NOT EXISTS `fpa-t-494007.so_rows.R20_GH` (
  input_id STRING,
  so_row_id STRING NOT NULL,
  session_id STRING,
  plan_type STRING,
  zblock_string STRING,
  io STRING NOT NULL,
  kr_type STRING,
  kr1 STRING, kr2 STRING, kr3 STRING, kr4 STRING,
  kr5 STRING, kr6 STRING, kr7 STRING, kr8 STRING,
  kr_code STRING, kr_name STRING,
  cdt1 STRING, cdt2 STRING, cdt3 STRING, cdt4 STRING,
  pt1 STRING, pt2 STRING, du STRING,
  pt1_prev STRING, pt2_prev STRING, du_prev STRING,
  own_type STRING,
  fu1_code STRING, fu2_code STRING,
  egt1 STRING, egt2 STRING, egt3 STRING, egt4 STRING, egt5 STRING,
  hr1 STRING, hr2 STRING, hr3 STRING,
  sec STRING, le1 STRING, le2 STRING,
  period STRING NOT NULL,
  value FLOAT64 NOT NULL,
  scenario STRING NOT NULL,
  role_source STRING NOT NULL,
  ppr_file_id STRING NOT NULL,
  track_variant STRING NOT NULL,
  alloc_znumber STRING,
  forecast_frequency STRING,
  noem_grade STRING,
  upload_batch_id STRING NOT NULL,
  created_by STRING NOT NULL,
  created_at TIMESTAMP NOT NULL
)
PARTITION BY DATE(created_at)
CLUSTER BY scenario, role_source, upload_batch_id;

CREATE TABLE IF NOT EXISTS `fpa-t-494007.so_rows.R20_HQ` (
  input_id STRING,
  so_row_id STRING NOT NULL,
  session_id STRING,
  plan_type STRING,
  zblock_string STRING,
  io STRING NOT NULL,
  kr_type STRING,
  kr1 STRING, kr2 STRING, kr3 STRING, kr4 STRING,
  kr5 STRING, kr6 STRING, kr7 STRING, kr8 STRING,
  kr_code STRING, kr_name STRING,
  cdt1 STRING, cdt2 STRING, cdt3 STRING, cdt4 STRING,
  pt1 STRING, pt2 STRING, du STRING,
  pt1_prev STRING, pt2_prev STRING, du_prev STRING,
  own_type STRING,
  fu1_code STRING, fu2_code STRING,
  egt1 STRING, egt2 STRING, egt3 STRING, egt4 STRING, egt5 STRING,
  hr1 STRING, hr2 STRING, hr3 STRING,
  sec STRING, le1 STRING, le2 STRING,
  period STRING NOT NULL,
  value FLOAT64 NOT NULL,
  scenario STRING NOT NULL,
  role_source STRING NOT NULL,
  ppr_file_id STRING NOT NULL,
  track_variant STRING NOT NULL,
  alloc_znumber STRING,
  forecast_frequency STRING,
  noem_grade STRING,
  upload_batch_id STRING NOT NULL,
  created_by STRING NOT NULL,
  created_at TIMESTAMP NOT NULL
)
PARTITION BY DATE(created_at)
CLUSTER BY scenario, role_source, upload_batch_id;

CREATE TABLE IF NOT EXISTS `fpa-t-494007.so_rows.R20_TECH` (
  input_id STRING,
  so_row_id STRING NOT NULL,
  session_id STRING,
  plan_type STRING,
  zblock_string STRING,
  io STRING NOT NULL,
  kr_type STRING,
  kr1 STRING, kr2 STRING, kr3 STRING, kr4 STRING,
  kr5 STRING, kr6 STRING, kr7 STRING, kr8 STRING,
  kr_code STRING, kr_name STRING,
  cdt1 STRING, cdt2 STRING, cdt3 STRING, cdt4 STRING,
  pt1 STRING, pt2 STRING, du STRING,
  pt1_prev STRING, pt2_prev STRING, du_prev STRING,
  own_type STRING,
  fu1_code STRING, fu2_code STRING,
  egt1 STRING, egt2 STRING, egt3 STRING, egt4 STRING, egt5 STRING,
  hr1 STRING, hr2 STRING, hr3 STRING,
  sec STRING, le1 STRING, le2 STRING,
  period STRING NOT NULL,
  value FLOAT64 NOT NULL,
  scenario STRING NOT NULL,
  role_source STRING NOT NULL,
  ppr_file_id STRING NOT NULL,
  track_variant STRING NOT NULL,
  alloc_znumber STRING,
  forecast_frequency STRING,
  noem_grade STRING,
  upload_batch_id STRING NOT NULL,
  created_by STRING NOT NULL,
  created_at TIMESTAMP NOT NULL
)
PARTITION BY DATE(created_at)
CLUSTER BY scenario, role_source, upload_batch_id;

CREATE TABLE IF NOT EXISTS `fpa-t-494007.so_rows.R20_COH_TER` (
  input_id STRING,
  so_row_id STRING NOT NULL,
  session_id STRING,
  plan_type STRING,
  zblock_string STRING,
  io STRING NOT NULL,
  kr_type STRING,
  kr1 STRING, kr2 STRING, kr3 STRING, kr4 STRING,
  kr5 STRING, kr6 STRING, kr7 STRING, kr8 STRING,
  kr_code STRING, kr_name STRING,
  cdt1 STRING, cdt2 STRING, cdt3 STRING, cdt4 STRING,
  pt1 STRING, pt2 STRING, du STRING,
  pt1_prev STRING, pt2_prev STRING, du_prev STRING,
  own_type STRING,
  fu1_code STRING, fu2_code STRING,
  egt1 STRING, egt2 STRING, egt3 STRING, egt4 STRING, egt5 STRING,
  hr1 STRING, hr2 STRING, hr3 STRING,
  sec STRING, le1 STRING, le2 STRING,
  period STRING NOT NULL,
  value FLOAT64 NOT NULL,
  scenario STRING NOT NULL,
  role_source STRING NOT NULL,
  ppr_file_id STRING NOT NULL,
  track_variant STRING NOT NULL,
  alloc_znumber STRING,
  forecast_frequency STRING,
  noem_grade STRING,
  upload_batch_id STRING NOT NULL,
  created_by STRING NOT NULL,
  created_at TIMESTAMP NOT NULL
)
PARTITION BY DATE(created_at)
CLUSTER BY scenario, role_source, upload_batch_id;

CREATE TABLE IF NOT EXISTS `fpa-t-494007.so_rows.R20_COH_VIS` (
  input_id STRING,
  so_row_id STRING NOT NULL,
  session_id STRING,
  plan_type STRING,
  zblock_string STRING,
  io STRING NOT NULL,
  kr_type STRING,
  kr1 STRING, kr2 STRING, kr3 STRING, kr4 STRING,
  kr5 STRING, kr6 STRING, kr7 STRING, kr8 STRING,
  kr_code STRING, kr_name STRING,
  cdt1 STRING, cdt2 STRING, cdt3 STRING, cdt4 STRING,
  pt1 STRING, pt2 STRING, du STRING,
  pt1_prev STRING, pt2_prev STRING, du_prev STRING,
  own_type STRING,
  fu1_code STRING, fu2_code STRING,
  egt1 STRING, egt2 STRING, egt3 STRING, egt4 STRING, egt5 STRING,
  hr1 STRING, hr2 STRING, hr3 STRING,
  sec STRING, le1 STRING, le2 STRING,
  period STRING NOT NULL,
  value FLOAT64 NOT NULL,
  scenario STRING NOT NULL,
  role_source STRING NOT NULL,
  ppr_file_id STRING NOT NULL,
  track_variant STRING NOT NULL,
  alloc_znumber STRING,
  forecast_frequency STRING,
  noem_grade STRING,
  upload_batch_id STRING NOT NULL,
  created_by STRING NOT NULL,
  created_at TIMESTAMP NOT NULL
)
PARTITION BY DATE(created_at)
CLUSTER BY scenario, role_source, upload_batch_id;

CREATE TABLE IF NOT EXISTS `fpa-t-494007.so_rows.R20_COH_SMI` (
  input_id STRING,
  so_row_id STRING NOT NULL,
  session_id STRING,
  plan_type STRING,
  zblock_string STRING,
  io STRING NOT NULL,
  kr_type STRING,
  kr1 STRING, kr2 STRING, kr3 STRING, kr4 STRING,
  kr5 STRING, kr6 STRING, kr7 STRING, kr8 STRING,
  kr_code STRING, kr_name STRING,
  cdt1 STRING, cdt2 STRING, cdt3 STRING, cdt4 STRING,
  pt1 STRING, pt2 STRING, du STRING,
  pt1_prev STRING, pt2_prev STRING, du_prev STRING,
  own_type STRING,
  fu1_code STRING, fu2_code STRING,
  egt1 STRING, egt2 STRING, egt3 STRING, egt4 STRING, egt5 STRING,
  hr1 STRING, hr2 STRING, hr3 STRING,
  sec STRING, le1 STRING, le2 STRING,
  period STRING NOT NULL,
  value FLOAT64 NOT NULL,
  scenario STRING NOT NULL,
  role_source STRING NOT NULL,
  ppr_file_id STRING NOT NULL,
  track_variant STRING NOT NULL,
  alloc_znumber STRING,
  forecast_frequency STRING,
  noem_grade STRING,
  upload_batch_id STRING NOT NULL,
  created_by STRING NOT NULL,
  created_at TIMESTAMP NOT NULL
)
PARTITION BY DATE(created_at)
CLUSTER BY scenario, role_source, upload_batch_id;

CREATE TABLE IF NOT EXISTS `fpa-t-494007.so_rows.R20_COH_AST` (
  input_id STRING,
  so_row_id STRING NOT NULL,
  session_id STRING,
  plan_type STRING,
  zblock_string STRING,
  io STRING NOT NULL,
  kr_type STRING,
  kr1 STRING, kr2 STRING, kr3 STRING, kr4 STRING,
  kr5 STRING, kr6 STRING, kr7 STRING, kr8 STRING,
  kr_code STRING, kr_name STRING,
  cdt1 STRING, cdt2 STRING, cdt3 STRING, cdt4 STRING,
  pt1 STRING, pt2 STRING, du STRING,
  pt1_prev STRING, pt2_prev STRING, du_prev STRING,
  own_type STRING,
  fu1_code STRING, fu2_code STRING,
  egt1 STRING, egt2 STRING, egt3 STRING, egt4 STRING, egt5 STRING,
  hr1 STRING, hr2 STRING, hr3 STRING,
  sec STRING, le1 STRING, le2 STRING,
  period STRING NOT NULL,
  value FLOAT64 NOT NULL,
  scenario STRING NOT NULL,
  role_source STRING NOT NULL,
  ppr_file_id STRING NOT NULL,
  track_variant STRING NOT NULL,
  alloc_znumber STRING,
  forecast_frequency STRING,
  noem_grade STRING,
  upload_batch_id STRING NOT NULL,
  created_by STRING NOT NULL,
  created_at TIMESTAMP NOT NULL
)
PARTITION BY DATE(created_at)
CLUSTER BY scenario, role_source, upload_batch_id;

CREATE TABLE IF NOT EXISTS `fpa-t-494007.so_rows.R20_COH_SAP` (
  input_id STRING,
  so_row_id STRING NOT NULL,
  session_id STRING,
  plan_type STRING,
  zblock_string STRING,
  io STRING NOT NULL,
  kr_type STRING,
  kr1 STRING, kr2 STRING, kr3 STRING, kr4 STRING,
  kr5 STRING, kr6 STRING, kr7 STRING, kr8 STRING,
  kr_code STRING, kr_name STRING,
  cdt1 STRING, cdt2 STRING, cdt3 STRING, cdt4 STRING,
  pt1 STRING, pt2 STRING, du STRING,
  pt1_prev STRING, pt2_prev STRING, du_prev STRING,
  own_type STRING,
  fu1_code STRING, fu2_code STRING,
  egt1 STRING, egt2 STRING, egt3 STRING, egt4 STRING, egt5 STRING,
  hr1 STRING, hr2 STRING, hr3 STRING,
  sec STRING, le1 STRING, le2 STRING,
  period STRING NOT NULL,
  value FLOAT64 NOT NULL,
  scenario STRING NOT NULL,
  role_source STRING NOT NULL,
  ppr_file_id STRING NOT NULL,
  track_variant STRING NOT NULL,
  alloc_znumber STRING,
  forecast_frequency STRING,
  noem_grade STRING,
  upload_batch_id STRING NOT NULL,
  created_by STRING NOT NULL,
  created_at TIMESTAMP NOT NULL
)
PARTITION BY DATE(created_at)
CLUSTER BY scenario, role_source, upload_batch_id;

CREATE TABLE IF NOT EXISTS `fpa-t-494007.so_rows.R20_CEH_TER_MAR` (
  input_id STRING,
  so_row_id STRING NOT NULL,
  session_id STRING,
  plan_type STRING,
  zblock_string STRING,
  io STRING NOT NULL,
  kr_type STRING,
  kr1 STRING, kr2 STRING, kr3 STRING, kr4 STRING,
  kr5 STRING, kr6 STRING, kr7 STRING, kr8 STRING,
  kr_code STRING, kr_name STRING,
  cdt1 STRING, cdt2 STRING, cdt3 STRING, cdt4 STRING,
  pt1 STRING, pt2 STRING, du STRING,
  pt1_prev STRING, pt2_prev STRING, du_prev STRING,
  own_type STRING,
  fu1_code STRING, fu2_code STRING,
  egt1 STRING, egt2 STRING, egt3 STRING, egt4 STRING, egt5 STRING,
  hr1 STRING, hr2 STRING, hr3 STRING,
  sec STRING, le1 STRING, le2 STRING,
  period STRING NOT NULL,
  value FLOAT64 NOT NULL,
  scenario STRING NOT NULL,
  role_source STRING NOT NULL,
  ppr_file_id STRING NOT NULL,
  track_variant STRING NOT NULL,
  alloc_znumber STRING,
  forecast_frequency STRING,
  noem_grade STRING,
  upload_batch_id STRING NOT NULL,
  created_by STRING NOT NULL,
  created_at TIMESTAMP NOT NULL
)
PARTITION BY DATE(created_at)
CLUSTER BY scenario, role_source, upload_batch_id;

CREATE TABLE IF NOT EXISTS `fpa-t-494007.so_rows.R20_CEH_TER_DEV` (
  input_id STRING,
  so_row_id STRING NOT NULL,
  session_id STRING,
  plan_type STRING,
  zblock_string STRING,
  io STRING NOT NULL,
  kr_type STRING,
  kr1 STRING, kr2 STRING, kr3 STRING, kr4 STRING,
  kr5 STRING, kr6 STRING, kr7 STRING, kr8 STRING,
  kr_code STRING, kr_name STRING,
  cdt1 STRING, cdt2 STRING, cdt3 STRING, cdt4 STRING,
  pt1 STRING, pt2 STRING, du STRING,
  pt1_prev STRING, pt2_prev STRING, du_prev STRING,
  own_type STRING,
  fu1_code STRING, fu2_code STRING,
  egt1 STRING, egt2 STRING, egt3 STRING, egt4 STRING, egt5 STRING,
  hr1 STRING, hr2 STRING, hr3 STRING,
  sec STRING, le1 STRING, le2 STRING,
  period STRING NOT NULL,
  value FLOAT64 NOT NULL,
  scenario STRING NOT NULL,
  role_source STRING NOT NULL,
  ppr_file_id STRING NOT NULL,
  track_variant STRING NOT NULL,
  alloc_znumber STRING,
  forecast_frequency STRING,
  noem_grade STRING,
  upload_batch_id STRING NOT NULL,
  created_by STRING NOT NULL,
  created_at TIMESTAMP NOT NULL
)
PARTITION BY DATE(created_at)
CLUSTER BY scenario, role_source, upload_batch_id;

CREATE TABLE IF NOT EXISTS `fpa-t-494007.so_rows.R20_CEH_TER_TECH` (
  input_id STRING,
  so_row_id STRING NOT NULL,
  session_id STRING,
  plan_type STRING,
  zblock_string STRING,
  io STRING NOT NULL,
  kr_type STRING,
  kr1 STRING, kr2 STRING, kr3 STRING, kr4 STRING,
  kr5 STRING, kr6 STRING, kr7 STRING, kr8 STRING,
  kr_code STRING, kr_name STRING,
  cdt1 STRING, cdt2 STRING, cdt3 STRING, cdt4 STRING,
  pt1 STRING, pt2 STRING, du STRING,
  pt1_prev STRING, pt2_prev STRING, du_prev STRING,
  own_type STRING,
  fu1_code STRING, fu2_code STRING,
  egt1 STRING, egt2 STRING, egt3 STRING, egt4 STRING, egt5 STRING,
  hr1 STRING, hr2 STRING, hr3 STRING,
  sec STRING, le1 STRING, le2 STRING,
  period STRING NOT NULL,
  value FLOAT64 NOT NULL,
  scenario STRING NOT NULL,
  role_source STRING NOT NULL,
  ppr_file_id STRING NOT NULL,
  track_variant STRING NOT NULL,
  alloc_znumber STRING,
  forecast_frequency STRING,
  noem_grade STRING,
  upload_batch_id STRING NOT NULL,
  created_by STRING NOT NULL,
  created_at TIMESTAMP NOT NULL
)
PARTITION BY DATE(created_at)
CLUSTER BY scenario, role_source, upload_batch_id;

CREATE TABLE IF NOT EXISTS `fpa-t-494007.so_rows.R20_CEH_VIS_MAR` (
  input_id STRING,
  so_row_id STRING NOT NULL,
  session_id STRING,
  plan_type STRING,
  zblock_string STRING,
  io STRING NOT NULL,
  kr_type STRING,
  kr1 STRING, kr2 STRING, kr3 STRING, kr4 STRING,
  kr5 STRING, kr6 STRING, kr7 STRING, kr8 STRING,
  kr_code STRING, kr_name STRING,
  cdt1 STRING, cdt2 STRING, cdt3 STRING, cdt4 STRING,
  pt1 STRING, pt2 STRING, du STRING,
  pt1_prev STRING, pt2_prev STRING, du_prev STRING,
  own_type STRING,
  fu1_code STRING, fu2_code STRING,
  egt1 STRING, egt2 STRING, egt3 STRING, egt4 STRING, egt5 STRING,
  hr1 STRING, hr2 STRING, hr3 STRING,
  sec STRING, le1 STRING, le2 STRING,
  period STRING NOT NULL,
  value FLOAT64 NOT NULL,
  scenario STRING NOT NULL,
  role_source STRING NOT NULL,
  ppr_file_id STRING NOT NULL,
  track_variant STRING NOT NULL,
  alloc_znumber STRING,
  forecast_frequency STRING,
  noem_grade STRING,
  upload_batch_id STRING NOT NULL,
  created_by STRING NOT NULL,
  created_at TIMESTAMP NOT NULL
)
PARTITION BY DATE(created_at)
CLUSTER BY scenario, role_source, upload_batch_id;

CREATE TABLE IF NOT EXISTS `fpa-t-494007.so_rows.R20_CEH_VIS_DEV` (
  input_id STRING,
  so_row_id STRING NOT NULL,
  session_id STRING,
  plan_type STRING,
  zblock_string STRING,
  io STRING NOT NULL,
  kr_type STRING,
  kr1 STRING, kr2 STRING, kr3 STRING, kr4 STRING,
  kr5 STRING, kr6 STRING, kr7 STRING, kr8 STRING,
  kr_code STRING, kr_name STRING,
  cdt1 STRING, cdt2 STRING, cdt3 STRING, cdt4 STRING,
  pt1 STRING, pt2 STRING, du STRING,
  pt1_prev STRING, pt2_prev STRING, du_prev STRING,
  own_type STRING,
  fu1_code STRING, fu2_code STRING,
  egt1 STRING, egt2 STRING, egt3 STRING, egt4 STRING, egt5 STRING,
  hr1 STRING, hr2 STRING, hr3 STRING,
  sec STRING, le1 STRING, le2 STRING,
  period STRING NOT NULL,
  value FLOAT64 NOT NULL,
  scenario STRING NOT NULL,
  role_source STRING NOT NULL,
  ppr_file_id STRING NOT NULL,
  track_variant STRING NOT NULL,
  alloc_znumber STRING,
  forecast_frequency STRING,
  noem_grade STRING,
  upload_batch_id STRING NOT NULL,
  created_by STRING NOT NULL,
  created_at TIMESTAMP NOT NULL
)
PARTITION BY DATE(created_at)
CLUSTER BY scenario, role_source, upload_batch_id;

CREATE TABLE IF NOT EXISTS `fpa-t-494007.so_rows.R20_CEH_SMI_MAR` (
  input_id STRING,
  so_row_id STRING NOT NULL,
  session_id STRING,
  plan_type STRING,
  zblock_string STRING,
  io STRING NOT NULL,
  kr_type STRING,
  kr1 STRING, kr2 STRING, kr3 STRING, kr4 STRING,
  kr5 STRING, kr6 STRING, kr7 STRING, kr8 STRING,
  kr_code STRING, kr_name STRING,
  cdt1 STRING, cdt2 STRING, cdt3 STRING, cdt4 STRING,
  pt1 STRING, pt2 STRING, du STRING,
  pt1_prev STRING, pt2_prev STRING, du_prev STRING,
  own_type STRING,
  fu1_code STRING, fu2_code STRING,
  egt1 STRING, egt2 STRING, egt3 STRING, egt4 STRING, egt5 STRING,
  hr1 STRING, hr2 STRING, hr3 STRING,
  sec STRING, le1 STRING, le2 STRING,
  period STRING NOT NULL,
  value FLOAT64 NOT NULL,
  scenario STRING NOT NULL,
  role_source STRING NOT NULL,
  ppr_file_id STRING NOT NULL,
  track_variant STRING NOT NULL,
  alloc_znumber STRING,
  forecast_frequency STRING,
  noem_grade STRING,
  upload_batch_id STRING NOT NULL,
  created_by STRING NOT NULL,
  created_at TIMESTAMP NOT NULL
)
PARTITION BY DATE(created_at)
CLUSTER BY scenario, role_source, upload_batch_id;

CREATE TABLE IF NOT EXISTS `fpa-t-494007.so_rows.R20_CEH_SMI_DEV` (
  input_id STRING,
  so_row_id STRING NOT NULL,
  session_id STRING,
  plan_type STRING,
  zblock_string STRING,
  io STRING NOT NULL,
  kr_type STRING,
  kr1 STRING, kr2 STRING, kr3 STRING, kr4 STRING,
  kr5 STRING, kr6 STRING, kr7 STRING, kr8 STRING,
  kr_code STRING, kr_name STRING,
  cdt1 STRING, cdt2 STRING, cdt3 STRING, cdt4 STRING,
  pt1 STRING, pt2 STRING, du STRING,
  pt1_prev STRING, pt2_prev STRING, du_prev STRING,
  own_type STRING,
  fu1_code STRING, fu2_code STRING,
  egt1 STRING, egt2 STRING, egt3 STRING, egt4 STRING, egt5 STRING,
  hr1 STRING, hr2 STRING, hr3 STRING,
  sec STRING, le1 STRING, le2 STRING,
  period STRING NOT NULL,
  value FLOAT64 NOT NULL,
  scenario STRING NOT NULL,
  role_source STRING NOT NULL,
  ppr_file_id STRING NOT NULL,
  track_variant STRING NOT NULL,
  alloc_znumber STRING,
  forecast_frequency STRING,
  noem_grade STRING,
  upload_batch_id STRING NOT NULL,
  created_by STRING NOT NULL,
  created_at TIMESTAMP NOT NULL
)
PARTITION BY DATE(created_at)
CLUSTER BY scenario, role_source, upload_batch_id;

CREATE TABLE IF NOT EXISTS `fpa-t-494007.so_rows.R20_CEH_AST_MAR` (
  input_id STRING,
  so_row_id STRING NOT NULL,
  session_id STRING,
  plan_type STRING,
  zblock_string STRING,
  io STRING NOT NULL,
  kr_type STRING,
  kr1 STRING, kr2 STRING, kr3 STRING, kr4 STRING,
  kr5 STRING, kr6 STRING, kr7 STRING, kr8 STRING,
  kr_code STRING, kr_name STRING,
  cdt1 STRING, cdt2 STRING, cdt3 STRING, cdt4 STRING,
  pt1 STRING, pt2 STRING, du STRING,
  pt1_prev STRING, pt2_prev STRING, du_prev STRING,
  own_type STRING,
  fu1_code STRING, fu2_code STRING,
  egt1 STRING, egt2 STRING, egt3 STRING, egt4 STRING, egt5 STRING,
  hr1 STRING, hr2 STRING, hr3 STRING,
  sec STRING, le1 STRING, le2 STRING,
  period STRING NOT NULL,
  value FLOAT64 NOT NULL,
  scenario STRING NOT NULL,
  role_source STRING NOT NULL,
  ppr_file_id STRING NOT NULL,
  track_variant STRING NOT NULL,
  alloc_znumber STRING,
  forecast_frequency STRING,
  noem_grade STRING,
  upload_batch_id STRING NOT NULL,
  created_by STRING NOT NULL,
  created_at TIMESTAMP NOT NULL
)
PARTITION BY DATE(created_at)
CLUSTER BY scenario, role_source, upload_batch_id;
